### ISSUE TITLE
Feature: Resizable popup

### ISSUE THREAD

**Issue by HZooly** [KeziahMoselle/tempus#37]
Hey ! I'm using Tempus on Windows 10 (I'll give a try on macOS this evening). I'd like to keep opened the popup (with percentage), but the window is too big. Is it feasible to resize it?

**Comment by KeziahMoselle** [comment]
Hey @HZooly,
Thank's for using Tempus !

Yes, I agree with you the window size is too large on 1080p screens and lower, I made the app with my 2K screen and I didn't thought about it until it was too late !

It's possible to fix this, as it will require a lot of refactoring (I did some errors for the layout) It will take some time ! but it's definitely an issue I want to fix !

**Comment by HZooly** [comment]
Cool to read that!

If you give some guidelines, I could give a try 😄

**Comment by KeziahMoselle** [comment]
You can give it a try if you want !

There is no special guidelines, as long as it's consistent !

**Comment by KeziahMoselle** [comment]
Feature #45 should do the trick instead of resizing the window (which can cause responsive issues)
