### ISSUE TITLE
Error when you click run

### ISSUE THREAD

**Issue by cjdduarte** [KeziahMoselle/tempus#39]
## Describe the bug
Error

## To Reproduce
1.  When you click run

## Screenshots

![image](https://user-images.githubusercontent.com/42243532/54379503-48986200-4668-11e9-8279-9b1daa31159e.png)

## Platform
Windows 10 - PT-BR

**Comment by KeziahMoselle** [comment]
Thank's for the report!

I'm currently debugging this ! A fix will soon be released

**Comment by cjdduarte** [comment]
Thank you

**Comment by KeziahMoselle** [comment]
This is fixed ! A release is coming soon
