### ISSUE TITLE
Feature: alternative window style

### ISSUE THREAD

**Issue by KeziahMoselle** [KeziahMoselle/tempus#45]
## Solution

A minimized window, clean and concise UI.
Showed on screen :

- Counter (% or min)
- Start/Stop counter
- Escape minimized UI

**Comment by stuajnht** [comment]
Hi,

I'll have a look at this if you're happy with the following mockup:
![tempus--issue-45--mockup](https://user-images.githubusercontent.com/13683986/66357153-b6d6a600-e965-11e9-8777-530a75b4977e.png)

**Comment by KeziahMoselle** [comment]
You are doing an amazing job !
It looks awesome 😍
Go for it !

**Comment by stuajnht** [comment]
Thanks @KeziahMoselle! You've made an awesome app, I'm just trying to help out where I can.

**Comment by KeziahMoselle** [comment]
Thank you 😊
