### ISSUE TITLE
The window size should be the same on 1080p screens

### ISSUE THREAD

**Issue by KeziahMoselle** [KeziahMoselle/tempus#60]
I built the app with a 2K resolution screen and it appears too big on 1080p screens
It should keep it's ratio

**Comment by manAbl** [comment]
Can I tackle this one?

**Comment by KeziahMoselle** [comment]
Yes you can !

**Comment by manAbl** [comment]
I don't know if this is relevant: 
[https://github.com/electron/electron/pull/18306](url), [https://github.com/electron/electron/pull/18306](url)

I'm trying to find a solution but I think I'm not understanding what I'm supposed to achieve. The aspect ratio seems fine to me

Maybe you can give an example image of how wide you want the app to be displayed as is was 2K window

**Comment by KeziahMoselle** [comment]
Hi !
I'm sorry I don't have my laptop for now, when i'll have it i'll upload a screenshot of it

**Comment by KeziahMoselle** [comment]
1080p screen : 
![preview](https://i.imgur.com/9tTc0JB.png)

How it should be : 
![preview](https://i.imgur.com/fFZ9ZIu.jpg)
