### ISSUE TITLE
Feature: change the way we set % or numeric values for the counter

### ISSUE THREAD

**Issue by KeziahMoselle** [KeziahMoselle/tempus#63]
![preview](https://i.imgur.com/fbm11Sg.png)

currently we need to click on the counter to change this setting, maybe there is a more intuitive way to do that

**Comment by stuajnht** [comment]
Hi,

How would you feel about having both counters showing at once, and you can click on them to make one or the other the "main" one? If so, I'm happy to have a go.

Please find a mockup below:
![tempus--issue-63--mockup](https://user-images.githubusercontent.com/13683986/66270411-33c12d00-e84b-11e9-8f07-9ed9d0945d44.png)

**Comment by KeziahMoselle** [comment]
it's a good idea !
