### ISSUE TITLE
Feature: Show seconds when the counter is under 1min

### ISSUE THREAD

**Issue by KeziahMoselle** [KeziahMoselle/tempus#64]
![preview](https://i.imgur.com/FS61qzh.png)

When the counter is under 1 minute it should display something like "40s" and not "0.4m"

**Comment by ConorGrocock** [comment]
I'd like to have a go at this

**Comment by KeziahMoselle** [comment]
Great ! Feel free 😄

**Comment by ConorGrocock** [comment]
Solved the issue in the above pull request

**Comment by KeziahMoselle** [comment]
I will look into that soon !
Thank you for your PR
