### ISSUE TITLE
Cannot build app

### ISSUE THREAD

**Issue by armaandh** [KeziahMoselle/tempus#93]
Trying to create an executable version of tempus (exe file) with electron builder, but it does not work. Clicking on the unpacked exe obtained from electron builder, I get the error below. 
![image](https://user-images.githubusercontent.com/8894156/87900803-3d96d400-ca0a-11ea-8027-07b9b1307190.png)

`yarn run build:electron` 

This is the command I ran to kick off the build process. Is there something I am missing?

**Comment by KeziahMoselle** [comment]
Hi @armaandh !

Thank you for the report, it is now fixed !
The app is under a huge refactoring since several months and I didn't have the time to take care of this project that much, sorry for this !

Cheers 🎉
